### ISSUE TITLE
extensionBridge.register() don't handle class instances

### ISSUE THREAD

**Issue by mems** [adobe/reactor-bridge#14]
I don't know if it's something desired, but if you provide a class instance for extension bridge registration this doesn't work as expected.

```js
class ExtensionView{
  constructor(vueSettings) {
    //...
  }
  init({extensionSettings}) {
    //...
  }

  getSettings() {
    //...
  }

  validate() {
    return false;
  }
}
class SomeExtensionView extends ExtensionView {
  constructor(vueSettings) {
    super(vueSettings);
  }
}

extensionBridge.register(new SomeExtensionView(someSettings));
```

You will get the error:

```
Unable to call init on the extension. The extension must register a init function using extensionBridge.register().
```

Only methods defined by the object itself are kept, inherited aren't, which is the case when you use class/prototype

The bridge child script when the extension is registered:

https://github.com/adobe/reactor-bridge/blob/30ca5c4bd5ca51709dfa384f38bc4a6d086bd230/src/child.js#L105-L108

And later when the method is called:

https://github.com/adobe/reactor-bridge/blob/30ca5c4bd5ca51709dfa384f38bc4a6d086bd230/src/child.js#L27-L30

**Comment by thebenrob** [comment]
Can you tell us more about your use case for using this in a class-based context?  Is there a problem that the documented methodology isn't solving for you?

**Comment by mems** [comment]
I'm using multiple views that share the same base class to handle common cases like settings validation etc.

```html
<awesome-resource-editor></awesome-resource-editor>
<script>
// imported
class ResourceEditor extends HTMLElement{
  getSettings() {
    return null;
  }
  validate() {
    return this.getSettings() != null;
  }
}
</script>
<script>
class AwesomeResourceEditor extends ResourceEditor{
  #input = null;
  constructor(){
    this.appendChild(Object.assign(this.#input = document.createElement("input"), {type: "date"}));
  }
  init() {/*...*/}
  getSettings() {
    const {value} = this.#input;
    return {value};
  }
  validate() {
    const settings = this.getSettings();
    return super.validate() && !Number.isNaN(Date.parse(settings?.value ?? ""));
  }
}
customElements.define("awesome-resource-editor", AwesomeResourceEditor);

// later
extensionBridge.register(document.querySelector("awesome-resource-editor"));// that doesn't work

// instead you need to
{
  const editor = document.querySelector("awesome-resource-editor");
  extensionBridge.register({
    init: editor.init.bind(editor),
    getSettings: editor.getSettings.bind(editor),
    validate: editor.validate.bind(editor),
  });
}
</script>
```

**Comment by jhicken** [comment]
It sounds like you want the register function to take a class instance `or` an object as its single argument. But Im still not entirely sure why. Are you trying to make your code look cleaner? 

It also makes me a bit nervous to change the function signature to take multiple different types as its argument. It feels safer to keep a single type to me. There is less ambiguity in how this function is used. And its more maintainable.


https://github.com/adobe/reactor-bridge/blob/master/src/child.js#L105
If you look at the code `register` is spreading the items off the argument. I suspect that's where your issue is. It comes down to this issue that an instantiated class just is not an object.

Is there a reason why you cannot do this?
```javascript
  const editor = document.querySelector("awesome-resource-editor");
  extensionBridge.register({
    init: editor.init.bind(editor),
    getSettings: editor.getSettings.bind(editor),
    validate: editor.validate.bind(editor),
  });
```

Sorry I want to help but im still not entirely sure of what problem you're trying to solve. And if is what I described above, I think I would prefer not to change the current API.

**Comment by thebenrob** [comment]
We do not want to support multiple patterns for doing the same thing and prefer to leave this as is.
